export * from './user.schema';
export * from './role.schema';
export * from './class.schema';
export * from './userData.schema';
export * from './score.schema';
export * from './subject.schema';
export * from './teacher.schema';
export * from './room.schema';
export * from './studentRegister.schema';
